ENV mongo_db_host=localhost
ENV mongo_db_port=27017
ENV mongo_db_db=test
ENV mongo_db_username=mongo
ENV mongo_db_password=mongo

FROM node:16.16-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -dev
COPY . .
RUN npm run build

FROM node:16.16-alpine as run
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /src/usr/app
COPY package*.json ./
RUN npm install -prod
COPY . .
COPY --from=build /usr/src/app/dist ./dist

CMD ["node", "dist/main"]
EXPOSE 3000
