FROM node:16.16-alpine as build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install -dev
COPY . .
RUN npm run build

FROM node:16.16-alpine as run
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /src/usr/app
COPY package*.json ./
RUN npm install -prod
COPY . .
COPY --from=build /usr/src/app/dist ./dist

ENV MONGO_DB_HOST=localhost
ENV MONGO_DB_PORT=27017
ENV MONGO_DB_DB=test
ENV MONGO_DB_USERNAME=mongo
ENV MONGO_DB_PASSWORD=mongo
CMD ["node", "dist/main"]
EXPOSE 3000
